### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by dwelle** [sindresorhus/shebang-regex#2]
I couldn't but notice the performance implications this greedy regex has (provided you ever use something else other than `#test`), so I made a quick [perf](http://jsperf.com/greedy-hashbang). 

Unless you have good reasons why the regex should consume the whole string (and not even break on spaces?), I'd remove the `.*` tail.

**Comment by arthurvr** [comment]
Well the use case is [`strip-shebang`](https://github.com/sindresorhus/strip-shebang).

**Comment by dwelle** [comment]
Then this package seems too much coupled with `strip-shebang` to be a standalone package that says nothing of its (true) purpose.

Edit: digging further, I see @sindresorhus created this package mainly to modularize [babel-core](https://github.com/babel/babel/commit/211c9802a51051f01738fb9f2a3d93e43f885804). So that was the original reason - to match and replace ~~hashbangs~~ shebang [lines]. But since there's not a note about this in README, you have no real idea what this package is really for. If I wanted to use it for simple matching, I'd get a _potentially_ huge performance hit for something I didn't want.

Edit2: Ok, not noticing the obvious - this package assumes that `shebang = shebang line`, which is not the case [[1]](http://en.wikipedia.org/wiki/Shebang_%28Unix%29), [[2]](http://unix.stackexchange.com/a/87600/101550). Probably a note somewhere would help with the confusion.

**Comment by sindresorhus** [comment]
The shebang isn't just the actual `!#`, but also the path to the bin. Greedy only matches the current line, so the perf difference is neglible. Micro benchmarks are useless.

**Comment by dwelle** [comment]
Yea, I know, the original reason for this perf issue was mainly a joke... until I realized it's not.

(the argument about this package readme not being obvious still stands, though)

**Comment by sindresorhus** [comment]
@dwelle It is a joke, please google about the fallacy of premature optimization and micro benchmarks.

I have however clarified the the readme ;) https://github.com/sindresorhus/shebang-regex/commit/a9b30979d97d2847cff7c7651ddabb245c4f58e0
